import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "SugarWOD + Zen Planner",
    description: "Generated by Untitled UI CLI",
    robots: "noindex, nofollow",
    icons: {
        icon: [
            { url: "/favicon/favicon.svg", type: "image/svg+xml" },
            { url: "/favicon/favicon-96x96.png", sizes: "96x96", type: "image/png" },
            { url: "/favicon/favicon.ico", sizes: "any" },
        ],
        apple: [
            { url: "/favicon/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
        ],
    },
    manifest: "/favicon/site.webmanifest",
};

export const viewport: Viewport = {
    themeColor: "#0a0d12",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, "bg-primary antialiased")}>
                <RouteProvider>
                    <Theme>{children}</Theme>
                </RouteProvider>
            </body>
        </html>
    );
}
